name: smile-detector
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7
  - pip=20.1.1
  - tensorflow
  - pillow
  - markdown
  - pip:
      - open-cv
      - flask
      - flask-sqlalchemy
      - jupyterlab
      - matplotlib
      - pandas
      - tqdm
